# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/k-clique

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/k-clique

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/k-clique/CMakeFiles /workspaces/k-clique//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/k-clique/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named k-clique

# Build rule for target.
k-clique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 k-clique
.PHONY : k-clique

# fast build rule for target.
k-clique/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/build
.PHONY : k-clique/fast

direct.o: direct.cu.o
.PHONY : direct.o

# target to build an object file
direct.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/direct.cu.o
.PHONY : direct.cu.o

direct.i: direct.cu.i
.PHONY : direct.i

# target to preprocess a source file
direct.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/direct.cu.i
.PHONY : direct.cu.i

direct.s: direct.cu.s
.PHONY : direct.s

# target to generate assembly for a file
direct.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/direct.cu.s
.PHONY : direct.cu.s

input.o: input.cu.o
.PHONY : input.o

# target to build an object file
input.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/input.cu.o
.PHONY : input.cu.o

input.i: input.cu.i
.PHONY : input.i

# target to preprocess a source file
input.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/input.cu.i
.PHONY : input.cu.i

input.s: input.cu.s
.PHONY : input.s

# target to generate assembly for a file
input.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/input.cu.s
.PHONY : input.cu.s

main.o: main.cu.o
.PHONY : main.o

# target to build an object file
main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/main.cu.o
.PHONY : main.cu.o

main.i: main.cu.i
.PHONY : main.i

# target to preprocess a source file
main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/main.cu.i
.PHONY : main.cu.i

main.s: main.cu.s
.PHONY : main.s

# target to generate assembly for a file
main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/main.cu.s
.PHONY : main.cu.s

orient.o: orient.cu.o
.PHONY : orient.o

# target to build an object file
orient.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/orient.cu.o
.PHONY : orient.cu.o

orient.i: orient.cu.i
.PHONY : orient.i

# target to preprocess a source file
orient.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/orient.cu.i
.PHONY : orient.cu.i

orient.s: orient.cu.s
.PHONY : orient.s

# target to generate assembly for a file
orient.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/orient.cu.s
.PHONY : orient.cu.s

pivot.o: pivot.cu.o
.PHONY : pivot.o

# target to build an object file
pivot.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/pivot.cu.o
.PHONY : pivot.cu.o

pivot.i: pivot.cu.i
.PHONY : pivot.i

# target to preprocess a source file
pivot.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/pivot.cu.i
.PHONY : pivot.cu.i

pivot.s: pivot.cu.s
.PHONY : pivot.s

# target to generate assembly for a file
pivot.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/k-clique.dir/build.make CMakeFiles/k-clique.dir/pivot.cu.s
.PHONY : pivot.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... k-clique"
	@echo "... direct.o"
	@echo "... direct.i"
	@echo "... direct.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... orient.o"
	@echo "... orient.i"
	@echo "... orient.s"
	@echo "... pivot.o"
	@echo "... pivot.i"
	@echo "... pivot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

